#
# pass for whitelisted (public) routes
# block for blacklisted routes
#
rules:
  pass:
    - api/v2/account/public
    - api/v2/account/identity
    - api/v2/exchange/public
    - api/v2/exchange/coinmarketcap
    - api/v2/exchange/coingecko
    - api/v2/ranger/public
    - api/v2/applogic/public
    - api/v2/arke/public
    - api/v2/sonic/public
  block:
    - api/v2/account/management
    - api/v2/exchange/management
